services:
  ai_server:
    container_name: hgp_ai_server
    build:
      context: ./requirements/ai_server
      dockerfile: Dockerfile
    image: hgp_ai_server_img
    # env_file: ./.env
    # depends_on:
    #   - game_management
    ports:
      - "3001:3001"
    networks:
      - hgp_network
    restart: unless-stopped

  front_end:
    container_name: hgp_front_end
    build:
      context: ./requirements/front_end
      dockerfile: Dockerfile
    image: hgp_front_end_img
    # env_file: ./.env
    # depends_on:
    #   - game_management
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
      - VITE_PONG_SERVER_BASE_URL=http://localhost:3003
      - VITE_AI_SERVER_BASE_URL=http://localhost:3001
    networks:
      - hgp_network
    restart: unless-stopped
    depends_on:
      - user_management
      - game_management

  game_management:
    container_name: hgp_game_management
    build:
      context: ./requirements/game_management
      dockerfile: Dockerfile
    image: hgp_game_management_img
    # env_file: ./.env
    # depends_on:
    #   - sqlite3
    ports:
      - "3003:3003"
    environment:
      - AI_SERVER_URL=http://hgp_ai_server:3001
    networks:
      - hgp_network
    restart: unless-stopped

  user_management:
    container_name: hgp_user_management
    build:
      context: ./requirements/user_management
      dockerfile: Dockerfile
    image: hgp_user_management_img
      # env_file: ./.env
      # depends_on:
      #   - sqlite3
      # volumes:
      #   - sqlite_data:/var/lib/sqlite
    ports:
      - "3000:3000"
    networks:
      - hgp_network
    restart: unless-stopped

  # nginx_proxy:
  #   container_name: hgp_gateway
  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: Dockerfile
  #   image: hgp_gateway_img
  #   ports:
  #     - "5173:80"
  #   networks:
  #     - hgp_network
  #   depends_on:
  #     - front_end
  #     - user_management
  #     # - game_management
  #   restart: always

volumes:
  sqlite_data:
    driver_opts:
      type: none
      device: /home/mgouraud/data/sqlite
      o: bind
  front_data:
    driver_opts:
      type: none
      device: /home/mgouraud/data/front

networks:
  hgp_network:
    driver: bridge
